### ISSUE TITLE
大佬有没有创建交流群啊

### ISSUE THREAD

**Issue by lujiex** [exbob/ssd1327_demo#1]
我想加入群里互相学习一下，从你的博客过来的。

**Comment by exbob** [comment]
没有，自己随便做点东西。群太水了，不如论坛博客。

**Comment by lujiex** [comment]
太谦虚了，我被nxp的yocto折磨几周了，看了你的博客，帮助很大！！如果可以的话，可以加个微信-。-

**Comment by exbob** [comment]
我恐怕没有精力帮你解决问题哦。
yocto门槛是稍高了一点，但是文档丰富，沉下心查文档多实践，理解了原理，问题不大。
我看你是做互联网的，怎么要高嵌入式啊？

**Comment by exbob** [comment]
我恐怕没有精力帮你解决问题哦。
yocto门槛是稍高了一点，但是文档丰富，沉下心查文档多实践，理解了原理，问题不大。
我看你是做互联网的，怎么要高嵌入式啊？

**Comment by lujiex** [comment]
有没有可能我是搞嵌入式的，其他只是随便搞搞

**Comment by lujiex** [comment]
这是我的博客，omnibots.cn，其实我想把你的博客转发到我的上面，哈哈！然后给你冠个名，加个友链

**Comment by exbob** [comment]
转载注明出处即可。
其实，最近在写一个更适合入门，更深入浅出的yocto教程

**Comment by lujiex** [comment]
强，期待yocto教程

**Comment by exbob** [comment]
https://shaocheng.li/posts/2023/12/30/
